name: Build Electron App

on:
  push:
    tags:
      - "v*" # åªæœ‰æ‰“ tag æ—¶è§¦å‘ï¼Œå¦‚ v1.0.0

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: ğŸ› ï¸ Checkout repository
        uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1
        with:
          tag: "${{ github.ref_name }}"
          fileName: "electron_bin_*.tar.gz"
          out-file-path: "resources/bin"
          extract: true

      - name: Display structure of downloaded files
        run: ls -R resources/bin

      - name: ğŸ“¦ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: ğŸ› ï¸ Install dependencies
        run: pnpm install

      - name: Package Electron app for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Running on Linux, packaging for Linux"
          pnpm run build:linux
          ls -alh out

      - name: Package Electron app for macOS
        if: matrix.os == 'macos-latest'
        run: |
          echo "Running on macOS"
          pnpm run build:mac
          ls -alh out

      - name: Package Electron app for Windows
        if: matrix.os == 'windows-latest'
        run: |
          Write-Host "Running on Windows"
          pnpm run build:win
          dir out

      - name: ğŸ“¤ Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EverkmNote-${{ matrix.os }}
          path: |
            out/EverkmNote*
            out/latest*.yml
            out/alpha*.yml
            out/beta*.yml
            out/rc*.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ğŸ› ï¸ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ“¥ Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: out/
          merge-multiple: true

      - name: Display structure of downloaded files
        run: |
          ls -alhR out

      - name: ğŸš€ Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload update files to Qiniu
        uses: saltbo/uptoc@v1.4.3
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QINIU_ACCESS_KEY }}
          UPTOC_UPLOADER_SK: ${{ secrets.QINIU_SECRET_KEY }}
        with:
          driver: qiniu
          region: cn-south-1 # ä¸ƒç‰›äº‘å­˜å‚¨åŒºåŸŸï¼Œæ ¹æ®å®é™…æƒ…å†µè°ƒæ•´
          bucket: dayu-assets
          dist: out
          saveroot: everkm-note/desktop # æ›´æ–°æ–‡ä»¶æ”¾åœ¨ä¸“é—¨çš„ç›®å½•
